services:
  - type: web
    name: blogify
    runtime: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: "0"
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: blogify-db
          property: connectionString
      - key: TINYMCE_API_KEY
        sync: false

databases:
  - name: blogify-db
    plan: free
    databaseName: blogify
    user: blogify
